language: go

before_install:
 - go get -v github.com/clevergo/router
 - go get -v github.com/clevergo/sessions
 - go get -v github.com/mattn/goveralls
 - go get -v github.com/valyala/fasthttp
 - go get -v golang.org/x/tools/cmd/cover

install:
 - go get -d -t -v ./...
 - go install -v

go:
 - 1.5
 - 1.6
 - 1.7
 - tip

script:
 - go test -v ./...
 - go test -v -covermode=count -coverprofile=coverage.out
 - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci

-after_success:
 - coveralls